import type { Vehicle } from './types';

/**
 * Catálogo seed: 4 modelos reais informados pela UVOLT + 10 modelos fictícios
 * para compor a demo comercial. Usado como fallback quando o Supabase
 * ainda não está configurado/povoado.
 */
export const seedVehicles: Vehicle[] = [
  {
    id: '1',
    name: 'MAX 12 MAJ',
    slug: 'max-12-maj',
    type: 'moto',
    tagline: 'Potência urbana sem limites',
    description:
      'A MAX 12 MAJ foi desenvolvida para quem exige desempenho real no dia a dia urbano de Salvador. Motor robusto, autonomia generosa e acabamento premium para encarar qualquer trajeto.',
    autonomy_km: 90,
    max_speed_kmh: 80,
    recharge_time: '4h (0-100%)',
    price: 14990,
    images: ['/vehicles/max-12-maj.svg'],
    colorway: ['#0A0A0C', '#3DA9FC'],
    status: 'available',
    created_at: '2025-01-10T00:00:00Z',
  },
  {
    id: '2',
    name: 'VITTORIA 2026',
    slug: 'vittoria-2026',
    type: 'moto',
    tagline: 'O futuro chegou antes',
    description:
      'A VITTORIA 2026 une design italiano e tecnologia de ponta. Painel digital, conectividade e uma presença de rua que chama atenção em qualquer esquina.',
    autonomy_km: 110,
    max_speed_kmh: 95,
    recharge_time: '5h (0-100%)',
    price: 18990,
    images: ['/vehicles/vittoria-2026.svg'],
    colorway: ['#16171A', '#A6F04A'],
    status: 'available',
    created_at: '2025-01-12T00:00:00Z',
  },
  {
    id: '3',
    name: 'RZ 110',
    slug: 'rz-110',
    type: 'moto',
    tagline: 'Velocidade redefinida',
    description:
      'A RZ 110 é a moto elétrica mais ágil do catálogo UVOLT. Construída para entregadores e motociclistas que não podem parar, com recarga rápida e chassi reforçado.',
    autonomy_km: 100,
    max_speed_kmh: 110,
    recharge_time: '3h30 (0-100%)',
    price: 16990,
    images: ['/vehicles/rz-110.svg'],
    colorway: ['#0A0A0C', '#FF6B35'],
    status: 'available',
    created_at: '2025-01-14T00:00:00Z',
  },
  {
    id: '4',
    name: 'M50 PRO',
    slug: 'm50-pro-aro-20',
    type: 'bike',
    tagline: 'Mobilidade leve, aro 20"',
    description:
      'A bicicleta elétrica M50 PRO foi pensada para o trajeto leve e inteligente. Aro 20", motor silencioso e bateria removível para recarregar onde quiser.',
    autonomy_km: 60,
    max_speed_kmh: 35,
    recharge_time: '3h (0-100%)',
    price: 6990,
    images: ['/vehicles/m50-pro.svg'],
    colorway: ['#1D1F23', '#7ED321'],
    status: 'available',
    created_at: '2025-01-15T00:00:00Z',
  },
  {
    id: '5',
    name: 'UVOLT X1 Urban',
    slug: 'x1-urban',
    type: 'moto',
    tagline: 'Feita para a cidade',
    description:
      'Compacta, ágil e eficiente. A X1 Urban entrega o equilíbrio perfeito entre autonomia e leveza para o trânsito de Salvador.',
    autonomy_km: 80,
    max_speed_kmh: 70,
    recharge_time: '4h (0-100%)',
    price: 12990,
    images: ['/vehicles/x1-urban.svg'],
    colorway: ['#0A0A0C', '#3DA9FC'],
    status: 'available',
    created_at: '2025-01-16T00:00:00Z',
  },
  {
    id: '6',
    name: 'UVOLT S9 Nitro',
    slug: 's9-nitro',
    type: 'moto',
    tagline: 'Adrenalina elétrica',
    description:
      'Performance esportiva com zero emissões. A S9 Nitro acelera forte e entrega resposta instantânea em qualquer marcha do dia.',
    autonomy_km: 95,
    max_speed_kmh: 105,
    recharge_time: '4h (0-100%)',
    price: 17990,
    images: ['/vehicles/s9-nitro.svg'],
    colorway: ['#16171A', '#FF6B35'],
    status: 'available',
    created_at: '2025-01-17T00:00:00Z',
  },
  {
    id: '7',
    name: 'UVOLT E-Rider 300',
    slug: 'e-rider-300',
    type: 'moto',
    tagline: 'Autonomia que impressiona',
    description:
      'A E-Rider 300 foi criada para quem rola longas distâncias sem abrir mão do conforto. Bateria de alta densidade e suspensão ajustável.',
    autonomy_km: 130,
    max_speed_kmh: 90,
    recharge_time: '5h30 (0-100%)',
    price: 19990,
    images: ['/vehicles/e-rider-300.svg'],
    colorway: ['#0A0A0C', '#A6F04A'],
    status: 'available',
    created_at: '2025-01-18T00:00:00Z',
  },
  {
    id: '8',
    name: 'UVOLT CityVolt 2025',
    slug: 'cityvolt-2025',
    type: 'moto',
    tagline: 'Inteligente. Silenciosa. Sua.',
    description:
      'A CityVolt 2025 traz conectividade via app, alarme inteligente e iluminação full LED para rodar com estilo pela cidade.',
    autonomy_km: 85,
    max_speed_kmh: 75,
    recharge_time: '4h (0-100%)',
    price: 13990,
    images: ['/vehicles/cityvolt-2025.svg'],
    colorway: ['#1D1F23', '#3DA9FC'],
    status: 'available',
    created_at: '2025-01-19T00:00:00Z',
  },
  {
    id: '9',
    name: 'UVOLT Falcon X',
    slug: 'falcon-x',
    type: 'moto',
    tagline: 'Aerodinâmica de elite',
    description:
      'Carenagem esportiva e centro de gravidade baixo. A Falcon X foi desenhada em túnel de vento para máxima estabilidade em alta velocidade.',
    autonomy_km: 105,
    max_speed_kmh: 115,
    recharge_time: '4h30 (0-100%)',
    price: 21990,
    images: ['/vehicles/falcon-x.svg'],
    colorway: ['#0A0A0C', '#FF9466'],
    status: 'available',
    created_at: '2025-01-20T00:00:00Z',
  },
  {
    id: '10',
    name: 'UVOLT NeoMotion 90',
    slug: 'neomotion-90',
    type: 'bike',
    tagline: 'Leveza em movimento',
    description:
      'Bicicleta elétrica compacta com quadro em liga de alumínio e pedalada assistida inteligente. Ideal para trajetos curtos e médios.',
    autonomy_km: 55,
    max_speed_kmh: 32,
    recharge_time: '2h30 (0-100%)',
    price: 5990,
    images: ['/vehicles/neomotion-90.svg'],
    colorway: ['#16171A', '#7ED321'],
    status: 'available',
    created_at: '2025-01-21T00:00:00Z',
  },
  {
    id: '11',
    name: 'UVOLT Pulse R',
    slug: 'pulse-r',
    type: 'moto',
    tagline: 'Resposta instantânea',
    description:
      'A Pulse R entrega torque imediato e um painel digital de alto contraste, feito para quem vive em movimento.',
    autonomy_km: 90,
    max_speed_kmh: 85,
    recharge_time: '4h (0-100%)',
    price: 15490,
    images: ['/vehicles/pulse-r.svg'],
    colorway: ['#0A0A0C', '#3DA9FC'],
    status: 'available',
    created_at: '2025-01-22T00:00:00Z',
  },
  {
    id: '12',
    name: 'UVOLT Vibe Electric',
    slug: 'vibe-electric',
    type: 'bike',
    tagline: 'O ritmo da cidade',
    description:
      'Design minimalista e motor de cubo silencioso. A Vibe Electric é a bike elétrica para quem busca praticidade com estilo.',
    autonomy_km: 50,
    max_speed_kmh: 30,
    recharge_time: '2h30 (0-100%)',
    price: 5490,
    images: ['/vehicles/vibe-electric.svg'],
    colorway: ['#1D1F23', '#A6F04A'],
    status: 'available',
    created_at: '2025-01-23T00:00:00Z',
  },
  {
    id: '13',
    name: 'UVOLT Storm E-Max',
    slug: 'storm-e-max',
    type: 'moto',
    tagline: 'Força bruta, zero ruído',
    description:
      'O motor mais potente da linha UVOLT. Storm E-Max é feita para quem precisa de capacidade de carga e potência sem comprometer a autonomia.',
    autonomy_km: 100,
    max_speed_kmh: 100,
    recharge_time: '5h (0-100%)',
    price: 18490,
    images: ['/vehicles/storm-e-max.svg'],
    colorway: ['#0A0A0C', '#FF6B35'],
    status: 'available',
    created_at: '2025-01-24T00:00:00Z',
  },
  {
    id: '14',
    name: 'UVOLT Urban Pro X',
    slug: 'urban-pro-x',
    type: 'moto',
    tagline: 'O equilíbrio perfeito',
    description:
      'Urban Pro X combina economia, conforto e tecnologia embarcada — a escolha ideal para quem usa a moto todos os dias.',
    autonomy_km: 88,
    max_speed_kmh: 78,
    recharge_time: '4h (0-100%)',
    price: 13490,
    images: ['/vehicles/urban-pro-x.svg'],
    colorway: ['#16171A', '#3DA9FC'],
    status: 'available',
    created_at: '2025-01-25T00:00:00Z',
  },
];
